name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: run
        uses: ./

      - run: test -n "${{ steps.run.outputs.node-build-version }}"
      - run: test "${{ steps.run.outputs.node-version }}" = "$(< .node-version)"

  test-with-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: run
        uses: ./
        with:
          node-version-path: .nvmrc

      - run: test -n "${{ steps.run.outputs.node-build-version }}"
      - run: test "${{ steps.run.outputs.node-version }}" = "$(< .nvmrc)"

  test-with-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: run
        continue-on-error: true
        uses: ./
        with:
          node-version: 999.999.999

      - run: test -n "${{ steps.run.outputs.node-build-version }}"
      - run: test "${{ steps.run.outputs.node-version }}" = "999.999.999"
      - run: test "${{ steps.run.outcome }}" = "failure"

  release:
    needs:
      - test-default
      - test-with-path
      - test-with-version
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
